services:
  global.customException:
    location: app/services/customExceptionService.js
  global.mail:
    location: app/services/mailService.js
  global.smtpConnect:
    location: app/services/smtpConnectService.js
  global.connectBD:
    location: app/services/connectBDService.js
  global.jsonResponseMessageBDService:
      location: app/services/jsonResponseMessageBDService.js
  global.sessionService:
        location: app/services/sessionService.js