services:
  global.customException:
    location: app/services/customExceptionService.js
    #parametrs: ['exception', 'message', 'code' : null]
  global.mail:
    location: app/services/mailService.js
  global.smtpConnect:
    location: app/services/smtpConnectService.js
    #parametrs: ['userEmailSander', 'password', 'host', 'port']
  global.connectBD:
    location: app/services/connectBDService.js